version: "3"

services:
  ldap:
    build: .
    ports:
      - 389:389 
      - 638:638 
    environment:
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
